name: test-and-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - develop

permissions:
  contents: read

jobs:
  lint:
    name: lint
    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x]
        linter-version: [1.46.2]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ matrix.linter-version }}

  test:
    name: test
    strategy:
      matrix:
        go-version: [ 1.17.x, 1.18.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v3
      - run: go test -v -race -cover -bench=. ./...
